name: release
on:
  push:
    tags:
      - '*'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_PREFIX: ${{ steps.get-package_prefix.outputs.PACKAGE_PREFIX }}
      TAG_NAME: ${{ steps.get-package_prefix.outputs.TAG_NAME }}
      HEAD_SHA_SHORT: ${{ steps.get-package_prefix.outputs.HEAD_SHA_SHORT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: get-package_prefix
        id: get-package_prefix
        run: |
          LIB_NAME=waifu2x-ncnn-vulkan-python
          TAG_NAME=$(git describe --abbrev=0 --tags)
          HEAD_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "::set-output name=PACKAGE_PREFIX::${LIB_NAME}-${TAG_NAME}"
          echo "::set-output name=TAG_NAME::${TAG_NAME}"
          echo "::set-output name=HEAD_SHA_SHORT::${HEAD_SHA_SHORT}"

  ubuntu-py39:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.PACKAGE_PREFIX }}-py39-ubuntu-x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: "1.2.162.0"
          key: vulkansdk-linux-x86_64-1.2.162.0
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          wget 'https://sdk.lunarg.com/sdk/download/1.2.162.0/linux/vulkansdk-linux-x86_64-1.2.162.0.tar.gz?Human=true' \
               -O vulkansdk-linux-x86_64-1.2.162.0.tar.gz
          tar -xf vulkansdk-linux-x86_64-1.2.162.0.tar.gz
          rm -rf 1.2.162.0/source 1.2.162.0/samples
          find 1.2.162.0 -type f | grep -v -E 'vulkan|glslang' | xargs rm
      - name: install-python
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --no-install-suggests \
                               python3.9 python3.9-dev
      - name: build
        run: |
          export VULKAN_SDK=`pwd`/1.2.162.0/x86_64
          mkdir build && cd build
          VERSION=`python3 -V 2>&1 | cut -d " " -f 2`
          PythonBin=`which python3`
          echo $VERSION
          echo $PythonBin
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DNCNN_VULKAN=ON \
                -DNCNN_BUILD_TOOLS=OFF \
                -DNCNN_BUILD_EXAMPLES=OFF \
                -DPYTHON_EXECUTABLE=${PythonBin}  \
                -DPYBIND11_FINDPYTHON=OFF \
                ../src
          cmake --build . -j 2
          cp libwaifu2x_vulkan.so waifu2x_vulkan.so
          strip -x waifu2x_vulkan.so
      - name: package
        run: |
          mkdir -p ${{ env.PACKAGENAME }}
          cp README.md LICENSE ${{ env.PACKAGENAME }}
          cp build/waifu2x_vulkan.so ${{ env.PACKAGENAME }}
          cp -r models test ${{ env.PACKAGENAME }}
          zip -9 -r $PACKAGENAME.zip $PACKAGENAME
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGENAME }}
          path: ${{ env.PACKAGENAME }}.zip

  openmp-macos:
    runs-on: macos-latest
    steps:
      - name: cache-openmp
        id: cache-openmp
        uses: actions/cache@v1
        with:
          path: openmp-install
          key: openmp-macos-release-11.0.0
      - name: checkout
        if: steps.cache-openmp.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
      - name: openmp
        if: steps.cache-openmp.outputs.cache-hit != 'true'
        run: |
          wget 'https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/openmp-11.0.0.src.tar.xz'
          tar -xf openmp-11.0.0.src.tar.xz
          cd openmp-11.0.0.src
          sed -i'' -e '/.size __kmp_unnamed_critical_addr/d' runtime/src/z_Linux_asm.S
          sed -i'' -e 's/__kmp_unnamed_critical_addr/___kmp_unnamed_critical_addr/g' runtime/src/z_Linux_asm.S
      - name: build
        if: steps.cache-openmp.outputs.cache-hit != 'true'
        run: |
          cd openmp-11.0.0.src
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=install \
                -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                -DLIBOMP_ENABLE_SHARED=OFF \
                -DLIBOMP_OMPT_SUPPORT=OFF \
                -DLIBOMP_USE_HWLOC=OFF \
                ..
          cmake --build . -j 2
          cmake --build . --target install
      - name: copy-out-library
        if: steps.cache-openmp.outputs.cache-hit != 'true'
        run: |
          cp -r openmp-11.0.0.src/build/install openmp-install
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: openmp-macos
          path: openmp-install

  macos-script-py39:
    needs: [setup]
    runs-on: macos-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.PACKAGE_PREFIX }}-py39-macos-x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: run-build-script
        run: |
          bash build_mac.sh
      - name: rename-and-package
        run: |
          cp -r \
            ${{ needs.setup.outputs.PACKAGE_PREFIX }}_${{ needs.setup.outputs.HEAD_SHA_SHORT }}-py39-macos \
            $PACKAGENAME
          zip -9 -r $PACKAGENAME.zip $PACKAGENAME
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGENAME }}
          path: ${{ env.PACKAGENAME }}.zip

  windows-py39:
    needs: [setup]
    runs-on: windows-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.PACKAGE_PREFIX }}-py39-windows-x64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: "VulkanSDK"
          key: VulkanSDK-1.2.162.0-Installer
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri `
            https://sdk.lunarg.com/sdk/download/1.2.162.0/windows/VulkanSDK-1.2.162.0-Installer.exe?Human=true `
            -OutFile VulkanSDK-1.2.162.0-Installer.exe
          7z x -aoa .\VulkanSDK-1.2.162.0-Installer.exe -oVulkanSDK
          Remove-Item .\VulkanSDK\Demos, `
                      .\VulkanSDK\Samples, `
                      .\VulkanSDK\Third-Party, `
                      .\VulkanSDK\Tools, `
                      .\VulkanSDK\Tools32, `
                      .\VulkanSDK\Bin32, `
                      .\VulkanSDK\Lib32 `
                      -Recurse
      - name: install-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: build
        run: |
          $Env:VULKAN_SDK=((Get-Location).Path + '\VulkanSDK')
          mkdir build; Set-Location .\build\
          $V=python -V 2>&1
          cmake -A x64 `
                -DNCNN_VULKAN=ON `
                -DNCNN_BUILD_TOOLS=OFF `
                -DNCNN_BUILD_EXAMPLES=OFF `
                -DPYTHON_EXECUTABLE="$($Env:pythonLocation + '\python.exe')" `
                -DPYBIND11_FINDPYTHON=OFF `
                ..\src
          Copy-Item -Verbose -Path "$($Env:pythonLocation + '\libs\python39.lib')" -Destination "$((Get-Location).Path)"
          cmake --build . --config Release -j 2
          Set-Location .\Release\
          Copy-Item waifu2x_vulkan.dll waifu2x_vulkan.pyd
      - name: package
        run: |
          mkdir ${{ env.PACKAGENAME }}
          Copy-Item -Verbose -Path "README.md" -Destination "${{ env.PACKAGENAME }}"
          Copy-Item -Verbose -Path "LICENSE" -Destination "${{ env.PACKAGENAME }}"
          Copy-Item -Verbose -Path "build\Release\waifu2x_vulkan.pyd" -Destination "${{ env.PACKAGENAME }}"
          Copy-Item -Verbose -Recurse -Path "models" -Destination "${{ env.PACKAGENAME }}"
          Copy-Item -Verbose -Recurse -Path "test" -Destination "${{ env.PACKAGENAME }}"
          7z a -r "$($Env:PACKAGENAME + '.zip')" "$($Env:PACKAGENAME)"
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGENAME }}
          path: ${{ env.PACKAGENAME }}.zip

  release:
    needs: [setup, ubuntu, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: create-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.setup.outputs.TAG_NAME }}
          release_name: ${{ needs.setup.outputs.TAG_NAME }}
          draft: true
          prerelease: true

      - name: upload-ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGENAME: ${{ needs.setup.outputs.PACKAGE_PREFIX }}-py39-ubuntu-x86_64
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PACKAGENAME }}/${{ env.PACKAGENAME }}.zip
          asset_name: ${{ env.PACKAGENAME }}.zip
          asset_content_type: application/zip

      - name: upload-macos-py39
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGENAME: ${{ needs.setup.outputs.PACKAGE_PREFIX }}-py39-macos-x86_64
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PACKAGENAME }}/${{ env.PACKAGENAME }}.zip
          asset_name: ${{ env.PACKAGENAME }}.zip
          asset_content_type: application/zip

      - name: upload-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGENAME: ${{ needs.setup.outputs.PACKAGE_PREFIX }}-py39-windows-x64
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PACKAGENAME }}/${{ env.PACKAGENAME }}.zip
          asset_name: ${{ env.PACKAGENAME }}.zip
          asset_content_type: application/zip
